version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: mysql
    container_name: desafio
    restart: unless-stopped
    tty: true
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
    volumes:
      - $HOME/Desktop/desafio/desafio.sql:/desafio.sql